# Generated by Django 2.2.24 on 2021-12-14 11:58

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_auto_20211209_0613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 16, 11, 58, 0, 495820, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
